In [1]:
# ============================================
# Import Required Libraries
# ============================================

# Data manipulation
import pandas as pd
import numpy as np

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Date and time handling
from datetime import datetime

# Display plots within the notebook
%matplotlib inline

# Optional: Improve the appearance of plots
sns.set_theme(style="whitegrid")

# Ignore warning messages
import warnings
warnings.filterwarnings('ignore')

In [2]:
# ============================================
# Load the Dataset
# ============================================

# Read the Excel dataset
df = pd.read_excel("E-Commerce DataSet.xlsx")

# Display the first five records
print("First Five Records:")
display(df.head())

# Check the dataset dimensions
print("Dataset Dimensions (Rows, Columns):", df.shape)

First Five Records:

,rec_id,order_id,order_date,shipped_at,prod_sku,prod_qty
0,3476212,FC__3__296__RS__657__1216__1308861465,2015-11-03 06:44:36,2015-11-05 02:56:08,ACCD6KQ3PRMMPJPT,1
1,3476204,FC__3__296__RS__616__1139__1308857858,2015-11-03 06:43:06,2015-11-03 15:28:51,IT-PB11K,1
2,3472447,FC__3__296__RS__664__1238__58147367,2015-10-31 18:30:00,2015-11-04 10:16:31,1786602,1
3,3634024,FC__3__2__RS__2__1__3006075214,2015-12-01 18:30:00,NaT,ROON_24533_02nd_Dec,1
4,3535415,FC__3__296__RS__652__1200__1325959053,2015-11-11 09:41:33,2015-11-12 14:44:55,Eve HL51 Yellow,1

Dataset Dimensions (Rows, Columns): (100000, 6)

In [3]:
# ============================================
# Initial Data Exploration
# ============================================

# Display dataset information
print("Dataset Information:")
df.info()

# Display data types
print("\nData Types:")
print(df.dtypes)

# View summary statistics for numerical columns
print("\nSummary Statistics (Numerical Columns):")
display(df.describe())

# View summary statistics for all columns (including categorical)
print("\nSummary Statistics (All Columns):")
display(df.describe(include='all'))

# Examine column names
print("\nColumn Names:")
print(df.columns.tolist())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   rec_id      100000 non-null  int64
 1   order_id    100000 non-null  object
 2   order_date  100000 non-null  datetime64[ns]
 3   shipped_at  88090 non-null   datetime64[ns]
 4   prod_sku    99987 non-null   object
 5   prod_qty    100000 non-null  int64
dtypes: datetime64[ns](2), int64(2), object(2)
memory usage: 4.6+ MB

Data Types:
rec_id                 int64
order_id              object
order_date    datetime64[ns]
shipped_at    datetime64[ns]
prod_sku              object
prod_qty               int64
dtype: object

Summary Statistics (Numerical Columns):

,rec_id,order_date,shipped_at,prod_qty
count,1.000000e+05,100000,88090,100000.000000
mean,3.520014e+06,2015-11-09 04:34:30.368420096,2015-11-11 06:25:23.637143808,1.419420
min,3.099867e+06,2011-10-22 08:01:00,2015-09-01 06:22:35,0.000000
25%,3.485312e+06,2015-11-03 08:57:27.249999872,2015-11-05 02:56:08,1.000000
50%,3.547906e+06,2015-11-13 07:32:30,2015-11-15 06:48:19,1.000000
75%,3.594183e+06,2015-11-22 18:30:00,2015-11-24 11:02:51,1.000000
max,3.635779e+06,2026-11-15 07:41:00,2015-12-03 09:27:12,1800.000000
std,1.075177e+05,NaN,NaN,9.248329

Summary Statistics (All Columns):

,rec_id,order_id,order_date,shipped_at,prod_sku,prod_qty
count,1.000000e+05,100000,100000,88090,99987,100000.000000
unique,NaN,85193,NaN,NaN,15442,NaN
top,NaN,FC__3__2__RS__69__61__54560846,NaN,NaN,ROON_24465_06th Oct_TV_2nd_Duplicate,NaN
freq,NaN,340,NaN,NaN,5778,NaN
mean,3.520014e+06,NaN,2015-11-09 04:34:30.368420096,2015-11-11 06:25:23.637143808,NaN,1.419420
min,3.099867e+06,NaN,2011-10-22 08:01:00,2015-09-01 06:22:35,NaN,0.000000
25%,3.485312e+06,NaN,2015-11-03 08:57:27.249999872,2015-11-05 02:56:08,NaN,1.000000
50%,3.547906e+06,NaN,2015-11-13 07:32:30,2015-11-15 06:48:19,NaN,1.000000
75%,3.594183e+06,NaN,2015-11-22 18:30:00,2015-11-24 11:02:51,NaN,1.000000
max,3.635779e+06,NaN,2026-11-15 07:41:00,2015-12-03 09:27:12,NaN,1800.000000
std,1.075177e+05,NaN,NaN,NaN,NaN,9.248329

Column Names:
['rec_id', 'order_id', 'order_date', 'shipped_at', 'prod_sku', 'prod_qty']

In [4]:
# ============================================
# Check Data Quality
# ============================================

# Identify missing values
print("Missing Values:")
display(df.isnull().sum())

# Calculate the percentage of missing values
print("\nPercentage of Missing Values:")
display((df.isnull().sum() / len(df) * 100).round(2))

# Check duplicate records
duplicate_count = df.duplicated().sum()

print("\nNumber of Duplicate Records:")
print(duplicate_count)

# Count unique values in each column
print("\nUnique Values in Each Column:")
display(df.nunique())

# Inspect inconsistent entries

# Check for product quantities less than or equal to zero
print("\nRecords with Product Quantity <= 0:")
display(df[df['prod_qty'] <= 0])

# Check for missing product SKUs
print("\nRecords with Missing Product SKU:")
display(df[df['prod_sku'].isnull()])

# Check for missing shipment dates
print("\nRecords with Missing Shipment Date:")
display(df[df['shipped_at'].isnull()].head())

# Check for order dates occurring after shipment dates
print("\nRecords where Order Date is After Shipment Date:")
display(df[df['order_date'] > df['shipped_at']])

Missing Values:

rec_id            0
order_id          0
order_date        0
shipped_at    11910
prod_sku         13
prod_qty          0
dtype: int64

Percentage of Missing Values:

rec_id         0.00
order_id       0.00
order_date     0.00
shipped_at    11.91
prod_sku       0.01
prod_qty       0.00
dtype: float64

Number of Duplicate Records:
0

Unique Values in Each Column:

rec_id        100000
order_id       85193
order_date     27486
shipped_at      5329
prod_sku       15442
prod_qty          88
dtype: int64

Records with Product Quantity <= 0:

,rec_id,order_id,order_date,shipped_at,prod_sku,prod_qty
21069,3623001,FC__6__281__RS__523__808__emtex(162)001,2015-11-30 06:49:02,2015-12-02 10:15:49,NaN,0
28705,3624525,FC__6__281__RS__523__808__emtex004,2015-11-30 10:44:46,2015-12-02 08:01:01,NaN,0
28706,3624524,FC__6__281__RS__523__808__emtex004,2015-11-30 10:44:46,2015-12-02 08:01:01,NaN,0
30169,3623176,FC__6__281__RS__523__808__Emtex(162)002,2015-11-30 07:03:13,2015-12-02 10:15:49,NaN,0
30183,3623173,FC__6__281__RS__523__808__Emtex(162)002,2015-11-30 07:03:13,2015-12-02 10:15:49,NaN,0
30312,3622999,FC__6__281__RS__523__808__emtex(162)001,2015-11-30 06:49:02,2015-12-02 10:15:49,NaN,0
30383,3623436,FC__6__281__RS__523__808__Emtex(162)003,2015-11-30 08:02:11,2015-12-02 10:15:49,NaN,0
30425,3623000,FC__6__281__RS__523__808__emtex(162)001,2015-11-30 06:49:02,2015-12-02 10:15:49,NaN,0
30445,3622997,FC__6__281__RS__523__808__emtex(162)001,2015-11-30 06:49:02,2015-12-02 10:15:49,NaN,0
30482,3623177,FC__6__281__RS__523__808__Emtex(162)002,2015-11-30 07:03:13,2015-12-02 10:15:49,NaN,0
30483,3623175,FC__6__281__RS__523__808__Emtex(162)002,2015-11-30 07:03:13,2015-12-02 10:15:49,NaN,0
30484,3623435,FC__6__281__RS__523__808__Emtex(162)003,2015-11-30 08:02:11,2015-12-02 10:15:49,NaN,0
30485,3623437,FC__6__281__RS__523__808__Emtex(162)003,2015-11-30 08:02:11,2015-12-02 10:15:49,NaN,0
65149,3519480,MPP__299__139__RS__299__333__403-7111977-0564306,2015-11-09 07:38:40,NaT,TAXM9350712139,0

Records with Missing Product SKU:

,rec_id,order_id,order_date,shipped_at,prod_sku,prod_qty
21069,3623001,FC__6__281__RS__523__808__emtex(162)001,2015-11-30 06:49:02,2015-12-02 10:15:49,NaN,0
28705,3624525,FC__6__281__RS__523__808__emtex004,2015-11-30 10:44:46,2015-12-02 08:01:01,NaN,0
28706,3624524,FC__6__281__RS__523__808__emtex004,2015-11-30 10:44:46,2015-12-02 08:01:01,NaN,0
30169,3623176,FC__6__281__RS__523__808__Emtex(162)002,2015-11-30 07:03:13,2015-12-02 10:15:49,NaN,0
30183,3623173,FC__6__281__RS__523__808__Emtex(162)002,2015-11-30 07:03:13,2015-12-02 10:15:49,NaN,0
30312,3622999,FC__6__281__RS__523__808__emtex(162)001,2015-11-30 06:49:02,2015-12-02 10:15:49,NaN,0
30383,3623436,FC__6__281__RS__523__808__Emtex(162)003,2015-11-30 08:02:11,2015-12-02 10:15:49,NaN,0
30425,3623000,FC__6__281__RS__523__808__emtex(162)001,2015-11-30 06:49:02,2015-12-02 10:15:49,NaN,0
30445,3622997,FC__6__281__RS__523__808__emtex(162)001,2015-11-30 06:49:02,2015-12-02 10:15:49,NaN,0
30482,3623177,FC__6__281__RS__523__808__Emtex(162)002,2015-11-30 07:03:13,2015-12-02 10:15:49,NaN,0
30483,3623175,FC__6__281__RS__523__808__Emtex(162)002,2015-11-30 07:03:13,2015-12-02 10:15:49,NaN,0
30484,3623435,FC__6__281__RS__523__808__Emtex(162)003,2015-11-30 08:02:11,2015-12-02 10:15:49,NaN,0
30485,3623437,FC__6__281__RS__523__808__Emtex(162)003,2015-11-30 08:02:11,2015-12-02 10:15:49,NaN,0

Records with Missing Shipment Date:

,rec_id,order_id,order_date,shipped_at,prod_sku,prod_qty
3,3634024,FC__3__2__RS__2__1__3006075214,2015-12-01 18:30:00,NaT,ROON_24533_02nd_Dec,1
17,3634027,FC__3__2__RS__2__1__3006075790,2015-12-01 18:30:00,NaT,ROON_21468_5th Jan,1
27,3634030,FC__3__2__RS__2__1__3006075235,2015-12-01 18:30:00,NaT,ROON_24531_02nd_Dec,1
28,3634031,FC__3__2__RS__2__1__3006074812,2015-12-01 18:30:00,NaT,ROON_24533_02nd_Dec,1
35,3463767,MPP__218__68__RS__218__271__403-0013478-2866724,2015-11-01 12:08:14,NaT,HIUCF0076,1

Records where Order Date is After Shipment Date:

,rec_id,order_id,order_date,shipped_at,prod_sku,prod_qty
44027,3596713,FC__6__293__RS__595__1080__OD104476641899752000,2019-11-15 11:13:00,2015-11-24 08:30:43,UMS0009,1
54402,3606152,FC__3__295__RS__554__898__BMJPO-1516-11-22826,2026-11-15 07:41:00,2015-11-26 08:05:11,AVPT100050-W28,1
54403,3606164,FC__3__295__RS__554__898__BMJPO-1516-11-22826,2026-11-15 07:41:00,2015-11-26 08:05:11,AVPT100107-8,1
54404,3606165,FC__3__295__RS__554__898__BMJPO-1516-11-22826,2026-11-15 07:41:00,2015-11-26 08:05:11,AVTN100019-L,1
54405,3606166,FC__3__295__RS__554__898__BMJPO-1516-11-22826,2026-11-15 07:41:00,2015-11-26 08:05:11,AVDR102589-12,1
54406,3606167,FC__3__295__RS__554__898__BMJPO-1516-11-22826,2026-11-15 07:41:00,2015-11-26 08:05:11,AVDR101989-14,1
54407,3606150,FC__3__295__RS__554__898__BMJPO-1516-11-22826,2026-11-15 07:41:00,2015-11-26 08:05:11,AVDR102130-16,1
54415,3606151,FC__3__295__RS__554__898__BMJPO-1516-11-22826,2026-11-15 07:41:00,2015-11-26 08:05:11,AVDR102206-6,1
54416,3606148,FC__3__295__RS__554__898__BMJPO-1516-11-22826,2026-11-15 07:41:00,2015-11-26 08:05:11,AVDR102306-6,1
54417,3606149,FC__3__295__RS__554__898__BMJPO-1516-11-22826,2026-11-15 07:41:00,2015-11-26 08:05:11,AVDR102318-16,1
54418,3606146,FC__3__295__RS__554__898__BMJPO-1516-11-22826,2026-11-15 07:41:00,2015-11-26 08:05:11,AVJM100007-M,1
54419,3606147,FC__3__295__RS__554__898__BMJPO-1516-11-22826,2026-11-15 07:41:00,2015-11-26 08:05:11,AVBL100555-M,1
54420,3606153,FC__3__295__RS__554__898__BMJPO-1516-11-22826,2026-11-15 07:41:00,2015-11-26 08:05:11,AVLN100128-34B,1
54421,3606154,FC__3__295__RS__554__898__BMJPO-1516-11-22826,2026-11-15 07:41:00,2015-11-26 08:05:11,AVLN100131-M,1
54522,3606158,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR102926-12,1
54523,3606159,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR103005-12,1
54524,3606156,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR103014-12,1
54525,3606157,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR103014-12,1
54526,3606162,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR103036-8,1
54527,3606163,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR103053-12,1
54528,3606160,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR103053-6,1
54529,3606161,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR103056-10,1
54530,3606155,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR103056-8,1
54531,3606169,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR102893-M,1
54532,3606170,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR102893-M,1
54533,3606171,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR102909-12,1
54534,3606172,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR102909-12,1
54535,3606173,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR102909-8,1
54536,3606174,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR102909-8,1
54537,3606175,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR102918-10,1
54538,3606176,FC__3__295__RS__554__898__BMJPO-1516-11-22828,2026-11-15 07:41:00,2015-11-26 08:06:51,AVDR102918-8,1
55762,3174788,FC__3__17__RS__391__842__100015820,2015-11-09 03:42:00,2015-09-14 07:10:12,4055262371708,1
58327,3171959,FC__6__293__RS__498__664__301538090,2015-10-09 12:30:00,2015-09-15 08:14:49,520SW,1
61783,3242559,FC__3__2__RS__151__184__200000799,2025-09-15 16:23:00,2015-09-26 10:31:07,TFPD51_8GB,1
61784,3242564,FC__3__2__RS__151__184__200000800,2025-09-15 16:23:00,2015-09-26 10:31:07,TFCM211,1
62423,3191891,FC__3__17__RS__391__842__100015864,2015-12-09 09:59:00,2015-09-15 12:18:47,4053984068739,1
63132,3242568,FC__3__2__RS__151__184__200000800,2025-09-15 16:23:00,2015-09-26 10:31:07,TFCM157,1
93725,3489132,FC__3__44__RS__82__71__3320893,2015-11-25 08:41:00,2015-11-04 11:42:43,DWP252,1

In [5]:
# ============================================
# Data Cleaning
# ============================================

# Create a copy of the original dataset
df_clean = df.copy()

# ----------------------------------
# Remove duplicate records
# ----------------------------------
df_clean.drop_duplicates(inplace=True)

# ----------------------------------
# Handle missing values
# ----------------------------------

# Fill missing shipped_at values with the median date
median_shipped_date = df_clean['shipped_at'].median()
df_clean['shipped_at'] = df_clean['shipped_at'].fillna(median_shipped_date)

# Fill missing prod_sku values with the mode
mode_sku = df_clean['prod_sku'].mode()[0]
df_clean['prod_sku'] = df_clean['prod_sku'].fillna(mode_sku)

# ----------------------------------
# Correct data types
# ----------------------------------
df_clean['order_date'] = pd.to_datetime(df_clean['order_date'])
df_clean['shipped_at'] = pd.to_datetime(df_clean['shipped_at'])
df_clean['prod_qty'] = df_clean['prod_qty'].astype(int)

# ----------------------------------
# Standardise text values
# ----------------------------------

# Remove leading/trailing spaces from order_id
df_clean['order_id'] = df_clean['order_id'].astype(str).str.strip()

# Convert prod_sku to string first, then remove spaces
df_clean['prod_sku'] = df_clean['prod_sku'].astype(str).str.strip()

# ----------------------------------
# Verify the cleaned dataset
# ----------------------------------
print("Dataset Shape After Cleaning:", df_clean.shape)

print("\nMissing Values After Cleaning:")
print(df_clean.isnull().sum())

print("\nDuplicate Records After Cleaning:")
print(df_clean.duplicated().sum())

print("\nData Types:")
print(df_clean.dtypes)

print("\nFirst Five Records After Cleaning:")
display(df_clean.head())

Dataset Shape After Cleaning: (100000, 6)

Missing Values After Cleaning:
rec_id        0
order_id      0
order_date    0
shipped_at    0
prod_sku      0
prod_qty      0
dtype: int64

Duplicate Records After Cleaning:
0

Data Types:
rec_id                 int64
order_id              object
order_date    datetime64[ns]
shipped_at    datetime64[ns]
prod_sku              object
prod_qty               int64
dtype: object

First Five Records After Cleaning:

,rec_id,order_id,order_date,shipped_at,prod_sku,prod_qty
0,3476212,FC__3__296__RS__657__1216__1308861465,2015-11-03 06:44:36,2015-11-05 02:56:08,ACCD6KQ3PRMMPJPT,1
1,3476204,FC__3__296__RS__616__1139__1308857858,2015-11-03 06:43:06,2015-11-03 15:28:51,IT-PB11K,1
2,3472447,FC__3__296__RS__664__1238__58147367,2015-10-31 18:30:00,2015-11-04 10:16:31,1786602,1
3,3634024,FC__3__2__RS__2__1__3006075214,2015-12-01 18:30:00,2015-11-15 06:48:19,ROON_24533_02nd_Dec,1
4,3535415,FC__3__296__RS__652__1200__1325959053,2015-11-11 09:41:33,2015-11-12 14:44:55,Eve HL51 Yellow,1

In [6]:
# ============================================
# Date and Time Conversion
# ============================================

# Convert order_date to datetime
df_clean['order_date'] = pd.to_datetime(
    df_clean['order_date'],
    errors='coerce'
)

# Convert shipped_at to datetime
df_clean['shipped_at'] = pd.to_datetime(
    df_clean['shipped_at'],
    errors='coerce'
)

# Check for invalid dates (NaT values)
print("Missing/Invalid Dates:")
print(df_clean[['order_date', 'shipped_at']].isnull().sum())

# Fill missing shipped_at dates with the median shipment date
median_shipped_date = df_clean['shipped_at'].median()
df_clean['shipped_at'] = df_clean['shipped_at'].fillna(median_shipped_date)

# Verify that all missing dates have been handled
print("\nMissing Dates After Handling:")
print(df_clean[['order_date', 'shipped_at']].isnull().sum())

# Display data types
print("\nData Types:")
print(df_clean[['order_date', 'shipped_at']].dtypes)

# Display the first five records
print("\nFirst Five Records:")
display(df_clean[['order_date', 'shipped_at']].head())

Missing/Invalid Dates:
order_date    0
shipped_at    0
dtype: int64

Missing Dates After Handling:
order_date    0
shipped_at    0
dtype: int64

Data Types:
order_date    datetime64[ns]
shipped_at    datetime64[ns]
dtype: object

First Five Records:

           order_date          shipped_at
0 2015-11-03 06:44:36 2015-11-05 02:56:08
1 2015-11-03 06:43:06 2015-11-03 15:28:51
2 2015-10-31 18:30:00 2015-11-04 10:16:31
3 2015-12-01 18:30:00 2015-11-15 06:48:19
4 2015-11-11 09:41:33 2015-11-12 14:44:55

In [7]:
# ============================================
# Feature Engineering
# ============================================

# Create a copy of the cleaned dataset
df_features = df_clean.copy()

# ----------------------------------
# Order Year
# ----------------------------------
df_features['order_year'] = df_features['order_date'].dt.year

# ----------------------------------
# Order Month
# ----------------------------------
df_features['order_month'] = df_features['order_date'].dt.month

# ----------------------------------
# Order Day
# ----------------------------------
df_features['order_day'] = df_features['order_date'].dt.day

# ----------------------------------
# Day of Week
# ----------------------------------
df_features['day_of_week'] = df_features['order_date'].dt.day_name()

# ----------------------------------
# Order Hour
# ----------------------------------
df_features['order_hour'] = df_features['order_date'].dt.hour

# ----------------------------------
# Shipping Delay (Hours)
# ----------------------------------
df_features['shipping_delay_hours'] = (
    (df_features['shipped_at'] - df_features['order_date'])
    .dt.total_seconds() / 3600
)

# ----------------------------------
# Shipping Delay (Days)
# ----------------------------------
df_features['shipping_delay_days'] = (
    (df_features['shipped_at'] - df_features['order_date'])
    .dt.total_seconds() / (24 * 3600)
)

# ----------------------------------
# Shipment Status
# ----------------------------------
df_features['shipment_status'] = np.where(
    df_features['shipped_at'].notna(),
    'Shipped',
    'Not Shipped'
)

# ----------------------------------
# Display the new features
# ----------------------------------
print("Dataset Shape After Feature Engineering:", df_features.shape)

print("\nNew Features Added:")
display(df_features[['order_year',
                     'order_month',
                     'order_day',
                     'day_of_week',
                     'order_hour',
                     'shipping_delay_hours',
                     'shipping_delay_days',
                     'shipment_status']].head())

print("\nFirst Five Records:")
display(df_features.head())

Dataset Shape After Feature Engineering: (100000, 14)

New Features Added:

,order_year,order_month,order_day,day_of_week,order_hour,shipping_delay_hours,shipping_delay_days,shipment_status
0,2015,11,3,Tuesday,6,44.192222,1.841343,Shipped
1,2015,11,3,Tuesday,6,8.762500,0.365104,Shipped
2,2015,10,31,Saturday,18,87.775278,3.657303,Shipped
3,2015,12,1,Tuesday,18,-395.694722,-16.487280,Shipped
4,2015,11,11,Wednesday,9,29.056111,1.210671,Shipped

First Five Records:

,rec_id,order_id,order_date,shipped_at,prod_sku,prod_qty,order_year,order_month,order_day,day_of_week,order_hour,shipping_delay_hours,shipping_delay_days,shipment_status
0,3476212,FC__3__296__RS__657__1216__1308861465,2015-11-03 06:44:36,2015-11-05 02:56:08,ACCD6KQ3PRMMPJPT,1,2015,11,3,Tuesday,6,44.192222,1.841343,Shipped
1,3476204,FC__3__296__RS__616__1139__1308857858,2015-11-03 06:43:06,2015-11-03 15:28:51,IT-PB11K,1,2015,11,3,Tuesday,6,8.762500,0.365104,Shipped
2,3472447,FC__3__296__RS__664__1238__58147367,2015-10-31 18:30:00,2015-11-04 10:16:31,1786602,1,2015,10,31,Saturday,18,87.775278,3.657303,Shipped
3,3634024,FC__3__2__RS__2__1__3006075214,2015-12-01 18:30:00,2015-11-15 06:48:19,ROON_24533_02nd_Dec,1,2015,12,1,Tuesday,18,-395.694722,-16.487280,Shipped
4,3535415,FC__3__296__RS__652__1200__1325959053,2015-11-11 09:41:33,2015-11-12 14:44:55,Eve HL51 Yellow,1,2015,11,11,Wednesday,9,29.056111,1.210671,Shipped

In [8]:
# ============================================
# Data Validation
# ============================================

# Verify data types
print("Data Types:")
print(df_features.dtypes)

# ----------------------------------
# Confirm missing values
# ----------------------------------
print("\nMissing Values:")
print(df_features.isnull().sum())

# ----------------------------------
# Check invalid product quantities
# ----------------------------------
print("\nRecords with Invalid Product Quantity (<= 0):")
display(df_features[df_features['prod_qty'] <= 0])

# ----------------------------------
# Check negative shipping delays
# ----------------------------------
print("\nRecords with Negative Shipping Delay:")
display(df_features[df_features['shipping_delay_days'] < 0].head())

print("\nTotal Negative Shipping Delays:",
      (df_features['shipping_delay_days'] < 0).sum())

# ----------------------------------
# Verify engineered features
# ----------------------------------
print("\nSummary of Engineered Features:")
display(df_features[['order_year',
                     'order_month',
                     'order_day',
                     'order_hour',
                     'shipping_delay_days']].describe())

# ----------------------------------
# Display final dataset information
# ----------------------------------
print("\nFinal Dataset Shape:", df_features.shape)

print("\nFirst Five Records:")
display(df_features.head())

Data Types:
rec_id                           int64
order_id                        object
order_date              datetime64[ns]
shipped_at              datetime64[ns]
prod_sku                        object
prod_qty                         int64
order_year                       int32
order_month                      int32
order_day                        int32
day_of_week                     object
order_hour                       int32
shipping_delay_hours           float64
shipping_delay_days            float64
shipment_status                 object
dtype: object

Missing Values:
rec_id                  0
order_id                0
order_date              0
shipped_at              0
prod_sku                0
prod_qty                0
order_year              0
order_month             0
order_day               0
day_of_week             0
order_hour              0
shipping_delay_hours    0
shipping_delay_days     0
shipment_status         0
dtype: int64

Records with Invalid Product Quantity (<= 0):

,rec_id,order_id,order_date,shipped_at,prod_sku,prod_qty,order_year,order_month,order_day,day_of_week,order_hour,shipping_delay_hours,shipping_delay_days,shipment_status
21069,3623001,FC__6__281__RS__523__808__emtex(162)001,2015-11-30 06:49:02,2015-12-02 10:15:49,ROON_24465_06th Oct_TV_2nd_Duplicate,0,2015,11,30,Monday,6,51.446389,2.143600,Shipped
28705,3624525,FC__6__281__RS__523__808__emtex004,2015-11-30 10:44:46,2015-12-02 08:01:01,ROON_24465_06th Oct_TV_2nd_Duplicate,0,2015,11,30,Monday,10,45.270833,1.886285,Shipped
28706,3624524,FC__6__281__RS__523__808__emtex004,2015-11-30 10:44:46,2015-12-02 08:01:01,ROON_24465_06th Oct_TV_2nd_Duplicate,0,2015,11,30,Monday,10,45.270833,1.886285,Shipped
30169,3623176,FC__6__281__RS__523__808__Emtex(162)002,2015-11-30 07:03:13,2015-12-02 10:15:49,ROON_24465_06th Oct_TV_2nd_Duplicate,0,2015,11,30,Monday,7,51.210000,2.133750,Shipped
30183,3623173,FC__6__281__RS__523__808__Emtex(162)002,2015-11-30 07:03:13,2015-12-02 10:15:49,ROON_24465_06th Oct_TV_2nd_Duplicate,0,2015,11,30,Monday,7,51.210000,2.133750,Shipped
30312,3622999,FC__6__281__RS__523__808__emtex(162)001,2015-11-30 06:49:02,2015-12-02 10:15:49,ROON_24465_06th Oct_TV_2nd_Duplicate,0,2015,11,30,Monday,6,51.446389,2.143600,Shipped
30383,3623436,FC__6__281__RS__523__808__Emtex(162)003,2015-11-30 08:02:11,2015-12-02 10:15:49,ROON_24465_06th Oct_TV_2nd_Duplicate,0,2015,11,30,Monday,8,50.227222,2.092801,Shipped
30425,3623000,FC__6__281__RS__523__808__emtex(162)001,2015-11-30 06:49:02,2015-12-02 10:15:49,ROON_24465_06th Oct_TV_2nd_Duplicate,0,2015,11,30,Monday,6,51.446389,2.143600,Shipped
30445,3622997,FC__6__281__RS__523__808__emtex(162)001,2015-11-30 06:49:02,2015-12-02 10:15:49,ROON_24465_06th Oct_TV_2nd_Duplicate,0,2015,11,30,Monday,6,51.446389,2.143600,Shipped
30482,3623177,FC__6__281__RS__523__808__Emtex(162)002,2015-11-30 07:03:13,2015-12-02 10:15:49,ROON_24465_06th Oct_TV_2nd_Duplicate,0,2015,11,30,Monday,7,51.210000,2.133750,Shipped
30483,3623175,FC__6__281__RS__523__808__Emtex(162)002,2015-11-30 07:03:13,2015-12-02 10:15:49,ROON_24465_06th Oct_TV_2nd_Duplicate,0,2015,11,30,Monday,7,51.210000,2.133750,Shipped
30484,3623435,FC__6__281__RS__523__808__Emtex(162)003,2015-11-30 08:02:11,2015-12-02 10:15:49,ROON_24465_06th Oct_TV_2nd_Duplicate,0,2015,11,30,Monday,8,50.227222,2.092801,Shipped
30485,3623437,FC__6__281__RS__523__808__Emtex(162)003,2015-11-30 08:02:11,2015-12-02 10:15:49,ROON_24465_06th Oct_TV_2nd_Duplicate,0,2015,11,30,Monday,8,50.227222,2.092801,Shipped
65149,3519480,MPP__299__139__RS__299__333__403-7111977-0564306,2015-11-09 07:38:40,2015-11-15 06:48:19,TAXM9350712139,0,2015,11,9,Monday,7,143.160833,5.965035,Shipped

Records with Negative Shipping Delay:

,rec_id,order_id,order_date,shipped_at,prod_sku,prod_qty,order_year,order_month,order_day,day_of_week,order_hour,shipping_delay_hours,shipping_delay_days,shipment_status
3,3634024,FC__3__2__RS__2__1__3006075214,2015-12-01 18:30:00,2015-11-15 06:48:19,ROON_24533_02nd_Dec,1,2015,12,1,Tuesday,18,-395.694722,-16.48728,Shipped
17,3634027,FC__3__2__RS__2__1__3006075790,2015-12-01 18:30:00,2015-11-15 06:48:19,ROON_21468_5th Jan,1,2015,12,1,Tuesday,18,-395.694722,-16.48728,Shipped
27,3634030,FC__3__2__RS__2__1__3006075235,2015-12-01 18:30:00,2015-11-15 06:48:19,ROON_24531_02nd_Dec,1,2015,12,1,Tuesday,18,-395.694722,-16.48728,Shipped
28,3634031,FC__3__2__RS__2__1__3006074812,2015-12-01 18:30:00,2015-11-15 06:48:19,ROON_24533_02nd_Dec,1,2015,12,1,Tuesday,18,-395.694722,-16.48728,Shipped
61,3634034,FC__3__2__RS__2__1__3006075202,2015-12-01 18:30:00,2015-11-15 06:48:19,ROON_24532_02nd_Dec,1,2015,12,1,Tuesday,18,-395.694722,-16.48728,Shipped

Total Negative Shipping Delays: 7129

Summary of Engineered Features:

,order_year,order_month,order_day,order_hour,shipping_delay_days
count,100000.00000,100000.000000,100000.00000,100000.000000,100000.000000
mean,2015.00068,10.791730,14.77159,14.167200,2.555301
std,0.23816,0.658436,9.23645,5.104259,87.376118
min,2011.00000,2.000000,1.00000,0.000000,-4006.983206
25%,2015.00000,11.000000,5.00000,10.000000,0.830498
50%,2015.00000,11.000000,15.00000,18.000000,1.615058
75%,2015.00000,11.000000,23.00000,18.000000,3.642911
max,2026.00000,12.000000,31.00000,23.000000,1466.359942

Final Dataset Shape: (100000, 14)

First Five Records:

,rec_id,order_id,order_date,shipped_at,prod_sku,prod_qty,order_year,order_month,order_day,day_of_week,order_hour,shipping_delay_hours,shipping_delay_days,shipment_status
0,3476212,FC__3__296__RS__657__1216__1308861465,2015-11-03 06:44:36,2015-11-05 02:56:08,ACCD6KQ3PRMMPJPT,1,2015,11,3,Tuesday,6,44.192222,1.841343,Shipped
1,3476204,FC__3__296__RS__616__1139__1308857858,2015-11-03 06:43:06,2015-11-03 15:28:51,IT-PB11K,1,2015,11,3,Tuesday,6,8.762500,0.365104,Shipped
2,3472447,FC__3__296__RS__664__1238__58147367,2015-10-31 18:30:00,2015-11-04 10:16:31,1786602,1,2015,10,31,Saturday,18,87.775278,3.657303,Shipped
3,3634024,FC__3__2__RS__2__1__3006075214,2015-12-01 18:30:00,2015-11-15 06:48:19,ROON_24533_02nd_Dec,1,2015,12,1,Tuesday,18,-395.694722,-16.487280,Shipped
4,3535415,FC__3__296__RS__652__1200__1325959053,2015-11-11 09:41:33,2015-11-12 14:44:55,Eve HL51 Yellow,1,2015,11,11,Wednesday,9,29.056111,1.210671,Shipped